# Generated by Django 5.0.7 on 2024-07-26 16:33

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='customer_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video_review',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='review_videos/'),
        ),
    ]
