# Generated by Django 5.0.7 on 2024-07-26 17:19

import cloudinary_storage.storage
import testimonial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_alter_post_image_alter_review_customer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='video_review',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='review_videos/', validators=[testimonial.models.simple_video_validator]),
        ),
    ]
